version: '3.8'

services:

  mongoexpress:
    container_name: mongoexpress
    restart:
      always
    image: 'mongo-express'
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - local

  mongodb:
    container_name: mongodb
    restart:
      always
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - ./docker/bitnami:/bitnami/mongodb
    env_file:
      - .env
    networks:
      - local

  server:
    container_name: server
    restart:
      always
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    networks:
      - local
    volumes:
      - "./server:/usr/src/app"
      - "./uploads:/uploads"
    depends_on:
      - mongodb
    env_file:
      - .env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: "npm run dev"

  frontend:
    container_name: frontend
    restart:
      always
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - '9001:9001'
    volumes:
      - "./frontend:/usr/src/app"
      - "./uploads:/uploads"
    depends_on:
      - server
      - mongodb
    networks:
      - local
    command: "npm run docker-dev"

networks:
  local: