version: '3.8'

services:

  mongoexpress:
    image: 'mongo-express'
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - local

  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - ./docker/bitnami:/bitnami/mongodb
    env_file:
      - .env
    networks:
      - local

  server:
    tty: true
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    networks:
      - local
    volumes:
      - "./server:${WORKING_DIR}/server"
    working_dir: ${WORKING_DIR}/server
    depends_on:
      - mongodb
    env_file:
      - .env
    expose:
      - "8000"
    ports:
      - 8000:8000

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - "./frontend:/usr/src/app"
    depends_on:
      - server
      - mongodb
    networks:
      - local
    env_file:
      - .env

networks:
  local: